services:
#   Application Producer
  kafka-producer:
    build: .
    container_name: kafka-producer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    restart: unless-stopped

  # Application Consumer
#  kafka-consumer:
#    build: ./kafka-consumer
#    container_name: kafka-consumer
#    depends_on:
#      - kafka
#    environment:
#      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
#    restart: unless-stopped